[[bin]]
name = "prettydiff"
required-features = ["cli"]

[package]
name = "prettydiff"
version = "0.6.5"
authors = ["Roman Koblov <penpen938@me.com>"]
edition = "2018"
description = "Side-by-side diff for two files"
categories = ["text-processing"]
keywords = ["diff", "text", "compare", "changes"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/romankoblov/prettydiff"
homepage = "https://github.com/romankoblov/prettydiff"
rust-version = "1.70"

[dependencies]
ansi_term.version = "0.12"
pad = "0.1.6"
prettytable-rs.version = "0.10.0"
structopt.version = "0.3"

prettytable-rs.optional = true
structopt.optional = true
term = "0.7.0"

[features]
cli = ["prettytable-rs", "structopt"]
default = ["cli"]

[patch.crates-io]
prettytable-rs = { git = "https://github.com/asomers/prettytable-rs.git", rev = "1e2c2d5c3" }
